services:
  feel:
    build: ./src
    ports:
      - "10020:10020"
      - "10019:10019"
    restart: unless-stopped
    environment:
      - FLAG=flag{redacted}
      - PORT=10020
      - HTTP_PORT=10019
      - PUBLIC_IP=localhost
      - FUNC_SIG_IS_SOLVED=isSolved()
      - SHARED_SECRET=redactedredacted
      - ENV=development
