name: Tests

on: [push, pull_request,workflow_dispatch]

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
         submodules: recursive 

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting for TemplateContractOne
        run: |
          cd contracts/TemplateContractOne
          forge soldeer install
          forge fmt --check

      - name: Check formatting for TemplateContractTwo
        run: |
          cd contracts/TemplateContractTwo
          forge soldeer install
          forge fmt --check